### ISSUE TITLE
Where do I put the config code ?

### ISSUE THREAD

**Issue by creative-eye-studio** [jahudka/posthtml-responsive-images#1]
Hello

Where do I put the config code in a Symfony project please ?

I talk about this
`{
  "plugins": {
    "posthtml-responsive-images": {
      "urlFormat": "{baseUrl}{basename}@{width}x{height}.{ext}",
      "presets": {
        "preset A": {
          "sources": [ 128, 256, 512 ],
          "sizes": [
            [ 560, "256px" ],
            [ "30vw" ]
          ],
          "aspectRatio": "1:1"
        }
      }
    }
  }
}`

Thanks in advance

**Comment by jahudka** [comment]
Hi, well, this is a [`posthtml`](https://www.npmjs.com/package/posthtml) plugin, it's got nothing to do with Symfony; I suppose there are ways you could use PostHTML (and this plugin) within a Symfony project, but I don't know much about that, it's been years since I've done anything in Symfony. If there's some kind of official PostHTML integration in Symfony, you'll have to consult its documentation to figure out how to enable and configure plugins. Typically though, PostHTML configuration is provided in a `.posthtmlrc` file in your project root directory, as described in this project's readme.
